site_name: Nextedy CHECKLIST
site_description: 'Extend your Work Items with an action able checklist items and stay clear on what still needs to be done to satisfy your workflow process.'
site_author: 'Nextedy'

nav:
    - Home: index.md
    - Download: download.md
    - Pricing: pricing.md 
    - Version History: changelog.md   
    - Support: support.md 
    - About: about.md

theme:
  name: 'material'
  font: false
  palette:
    primary: 'black'
    accent: 'purple'
  favicon: img/favicon.png
  custom_dir: 'theme'
  logo: 'https://www.nextedy.com/wp-content/uploads/2018/10/nextedy-logo.png'

extra_css:
  - 'extra/extra.css'

extra_javascript:
  - 'extra/extra.js'
  
markdown_extensions:
  - admonition
  - codehilite
  - meta
  - tables
  - attr_list
  
copyright: 'Copyright &copy; 2020 Nextedy Systems'
  